### PR TITLE
feat: add past days class

### PR DESCRIPTION
**Pull request by yoyurec**
Add past days class to have different dimmed style
image

### CODE REVIEW

**Comment by vipzhicheng** [comment]
seems to only work for the current month, when switching to a past month, it lost the past style.

**Comment by yoyurec** [comment]
yes, other months not so important and not shows so often. was not intended.
should i extend?

**Comment by vipzhicheng** [comment]
Yes, I think it's better to make it consistent, if support past days, past days should have same styles.

**Comment by vipzhicheng** [comment]
Cool! I noticed some themes may overwrite the past day's color like "things" on the sidebar placeholder. But ok for now.

**Pull request merged**
